remove nerpa reference since its deprecated
filecoin-project/filecoin-docs pull request #1049
Opened 2021-09-18 13:15 UTC by jennijuju

2021-09-18 13:19 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build /home/runner/work/filecoin-docs/filecoin-docs
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links /home/runner/work/filecoin-docs/filecoin-docs
> vuepress check-md docs


Checking markdown...

3 dead links was found

  Hash is not found: [Storage/Deals status](#storagedeals-status) (/home/runner/work/filecoin-docs/filecoin-docs/docs/reference/README.md:19:7)
  Hash should slugify: [APIs & Developer tools](#apis--developer-tools) (/home/runner/work/filecoin-docs/filecoin-docs/docs/reference/README.md:21:5)
  Hash should slugify: [Node Infrastructure & APIs](#node-infrastructure--apis) (/home/runner/work/filecoin-docs/filecoin-docs/docs/reference/README.md:25:7)

Executes with --fix to fix automatically

Checking failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:links: `vuepress check-md docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:links script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-09-18T13_19_33_151Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:build: `npm run docs:links && vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-09-18T13_19_33_168Z-debug.log
```

2021-09-19 18:01 UTC, johnnymatthews requested changes
Added two suggestions. Apart from those two, this is a good PR and ready to merge.

2021-09-19 18:01 UTC, johnnymatthews commented on docs/mine/hardware-requirements.md
> +These are computationally expensive operations which depend on the sector sizes used by the [Filecoin network](https://network.filecoin.io) on which the miner is running -, testnet, mainnet etc.-. Fo
```suggestion
The Filecoin network requires storage providers to run computationally expensive operations. The cost of these operations depends on which network the storage provider is running; some testnets use a smaller sector size to increase the speeds of transactions artificially. For reference, the requirements listed below correspond to **32GiB sectors**, as used by mainnet and some testnets.
```

2021-09-20 14:15 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/get-started/lotus/chain.md`:
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ... Filecoin's blockchain grows relatively fast and a full sync will take a lon...
                                             ^^^^
  ```
- This phrase is duplicated. You should probably leave only “Current block”.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...t height State start height Lightweight Current block Current block - 2000 b...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...2000 blocks Current block - 2000 blocks Full chain Current block Genesis blo...
                                             ^^^^
  ```
- The verb “double-check” is spelled with a hyphen.<!--CategoryID:GRAMMAR, RuleID: DOUBLE_HYPHEN-->
  ```
  ...rily, and may not be up-to-date. Please double check before using them. Cali...
                                             ^^^^^^^^^^^^
  ```
- A determiner may be missing.<!--CategoryID:GRAMMAR, RuleID: THE_SUPERLATIVE-->
  ```
  ...efore using them. Calibration: Download latest snapshot: lotus_cali_snapshot...
                                             ^^^^^^
  ```
- Do not mix variants of the same word (‘synch’ and ‘sync’) within a single text.<!--CategoryID:MISC, RuleID: EN_WORD_COHERENCY-->
  ```
  ...ways to check your Lotus daemon's chain synching progress. # Sync status Use...
                                             ^^^^^^^^
  ```
- ‘wait’ (anticipate or expect something) seems less likely than ‘weight’ (mass).<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_WAIT_WEIGHT-->
  ```
  ...rrent state of your local chain: # Sync wait Use sync wait to output the sta...
                                             ^^^^
  ```
- Did you mean “to back up”?<!--CategoryID:TYPOS, RuleID: CAN_BACKUP-->
  ```
  ...ith how many state roots you would like to backup: To create a pruned snapsh...
                                             ^^^^^^^^^
  ```
### `docs/get-started/lotus/installation.md`:
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/lotus/releases/latest
- The following link returned HTTP status code 405 (Method Not Allowed):
  https://golang.org/dl/
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ing Amazon Web Services, are covered in Running in the cloud. # Minimal requ...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  .... # Minimal requirements To run a Lotus node your computer must have: macOS ...
                                             ^^^^
  ```
- Insert a space between the numerical value and the unit symbol.<!--CategoryID:PUNCTUATION, RuleID: UNIT_SPACE-->
  ```
  ...und 33Gib.  The full history was around 10TiB in June of 2021. WARNING These...
                                             ^^^^^
  ```
- When specifying a month and year, ‘of’ is unnecessary.<!--CategoryID:NONSTANDARD_PHRASES, RuleID: MONTH_OF_XXXX-->
  ```
  ....  The full history was around 10TiB in June of 2021. WARNING These are the ...
                                             ^^^^^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...cal/go/bin to your path. For most Linux distributions you can run something ...
                                             ^^^^^^^^^^^^^
  ```
- A word may be missing after ‘a’.<!--CategoryID:GRAMMAR, RuleID: THE_SENT_END-->
  ```
  ...xport additional environment variables: a. If you have an AMD Zen or Intel I...
                                             ^^
  ```
- A word may be missing after ‘a’.<!--CategoryID:GRAMMAR, RuleID: THE_SENT_END-->
  ```
  ...adding these two environment variables: a. Some older Intel and AMD processo...
                                             ^^
  ```
- A word may be missing after ‘a’.<!--CategoryID:GRAMMAR, RuleID: THE_SENT_END-->
  ```
  ...dd the CGO_CFLAGS environment variable: a. By default, a 'multicore-sdr' opt...
                                             ^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...a 'multicore-sdr' option is used in the proofs library.  This feature is als...
                                             ^^^^^^
  ```
- The operating system from Apple is written “macOS”.<!--CategoryID:GRAMMAR, RuleID: MAC_OS-->
  ```
  ...efault and not visible in journalctl. # MacOS These instructions are specifi...
                                             ^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...by building from source. # Install with Homebrew You can quickly install Lot...
                                             ^^^^^^^^
  ```
- The verb ‘check out’ is spelled as two words. The noun ‘checkout’ is spelled as one.<!--CategoryID:TYPOS, RuleID: CAN_CHECKOUT-->
  ```
  ...sitory:  Run git checkout <RELEASE TAG> to checkout to the latest Lotus rele...
                                             ^^^^^^^^^^^
  ```
- The verb ‘check out’ is spelled as two words. The noun ‘checkout’ is spelled as one.<!--CategoryID:TYPOS, RuleID: CAN_CHECKOUT-->
  ```
  ...GitHub release page  (opens new window) to checkout to that specific release...
                                             ^^^^^^^^^^^
  ```
- The verb ‘check out’ is spelled as two words. The noun ‘checkout’ is spelled as one.<!--CategoryID:TYPOS, RuleID: CAN_CHECKOUT-->
  ```
  ... that specific release. TIP If you want to checkout to a network other than ...
                                             ^^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... other than mainnet, take a look at the Switching networks guide → Create ne...
                                             ^^^^^^^^^
  ```
- Possibly missing article found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_THE-->
  ```
  ...t the Switching networks guide → Create necessary environment variable to al...
                                             ^^^^^^^^^
  ```
- The verb ‘check out’ is spelled as two words. The noun ‘checkout’ is spelled as one.<!--CategoryID:TYPOS, RuleID: CAN_CHECKOUT-->
  ```
  ...sitory:  Run git checkout <RELEASE TAG> to checkout to the latest Lotus rele...
                                             ^^^^^^^^^^^
  ```
- The verb ‘check out’ is spelled as two words. The noun ‘checkout’ is spelled as one.<!--CategoryID:TYPOS, RuleID: CAN_CHECKOUT-->
  ```
  ...GitHub release page  (opens new window) to checkout to that specific release...
                                             ^^^^^^^^^^^
  ```
- The verb ‘check out’ is spelled as two words. The noun ‘checkout’ is spelled as one.<!--CategoryID:TYPOS, RuleID: CAN_CHECKOUT-->
  ```
  ... that specific release. TIP If you want to checkout to a network other than ...
                                             ^^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... other than mainnet, take a look at the Switching networks guide → If you ar...
                                             ^^^^^^^^^
  ```
- Unpaired symbol: ‘"’ seems to be missing<!--CategoryID:PUNCTUATION, RuleID: EN_UNPAIRED_BRACKETS-->
  ```
  ... at some tips for running Lotus in China". Some older Intel and AMD processo...
                                             ^
  ```
- The ph [...]

2021-09-20 14:21 UTC, filecorgi commented
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/get-started/lotus/chain.md`:
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ... Filecoin's blockchain grows relatively fast and a full sync will take a lon...
                                             ^^^^
  ```
- This phrase is duplicated. You should probably leave only “Current block”.<!--CategoryID:GRAMMAR, RuleID: PHRASE_REPETITION-->
  ```
  ...t height State start height Lightweight Current block Current block - 2000 b...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...2000 blocks Current block - 2000 blocks Full chain Current block Genesis blo...
                                             ^^^^
  ```
- The verb “double-check” is spelled with a hyphen.<!--CategoryID:GRAMMAR, RuleID: DOUBLE_HYPHEN-->
  ```
  ...rily, and may not be up-to-date. Please double check before using them. Cali...
                                             ^^^^^^^^^^^^
  ```
- A determiner may be missing.<!--CategoryID:GRAMMAR, RuleID: THE_SUPERLATIVE-->
  ```
  ...efore using them. Calibration: Download latest snapshot: lotus_cali_snapshot...
                                             ^^^^^^
  ```
- Do not mix variants of the same word (‘synch’ and ‘sync’) within a single text.<!--CategoryID:MISC, RuleID: EN_WORD_COHERENCY-->
  ```
  ...ways to check your Lotus daemon's chain synching progress. # Sync status Use...
                                             ^^^^^^^^
  ```
- ‘wait’ (anticipate or expect something) seems less likely than ‘weight’ (mass).<!--CategoryID:TYPOS, RuleID: CONFUSION_RULE_WAIT_WEIGHT-->
  ```
  ...rrent state of your local chain: # Sync wait Use sync wait to output the sta...
                                             ^^^^
  ```
- Did you mean “to back up”?<!--CategoryID:TYPOS, RuleID: CAN_BACKUP-->
  ```
  ...ith how many state roots you would like to backup: To create a pruned snapsh...
                                             ^^^^^^^^^
  ```
### `docs/get-started/lotus/installation.md`:
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/lotus/releases/latest
- The following link returned HTTP status code 405 (Method Not Allowed):
  https://golang.org/dl/
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ...ing Amazon Web Services, are covered in Running in the cloud. # Minimal requ...
                                             ^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  .... # Minimal requirements To run a Lotus node your computer must have: macOS ...
                                             ^^^^
  ```
- Insert a space between the numerical value and the unit symbol.<!--CategoryID:PUNCTUATION, RuleID: UNIT_SPACE-->
  ```
  ...und 33Gib.  The full history was around 10TiB in June of 2021. WARNING These...
                                             ^^^^^
  ```
- When specifying a month and year, ‘of’ is unnecessary.<!--CategoryID:NONSTANDARD_PHRASES, RuleID: MONTH_OF_XXXX-->
  ```
  ....  The full history was around 10TiB in June of 2021. WARNING These are the ...
                                             ^^^^^^^^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...cal/go/bin to your path. For most Linux distributions you can run something ...
                                             ^^^^^^^^^^^^^
  ```
- A word may be missing after ‘a’.<!--CategoryID:GRAMMAR, RuleID: THE_SENT_END-->
  ```
  ...xport additional environment variables: a. If you have an AMD Zen or Intel I...
                                             ^^
  ```
- A word may be missing after ‘a’.<!--CategoryID:GRAMMAR, RuleID: THE_SENT_END-->
  ```
  ...adding these two environment variables: a. Some older Intel and AMD processo...
                                             ^^
  ```
- A word may be missing after ‘a’.<!--CategoryID:GRAMMAR, RuleID: THE_SENT_END-->
  ```
  ...dd the CGO_CFLAGS environment variable: a. By default, a 'multicore-sdr' opt...
                                             ^^
  ```
- An apostrophe may be missing.<!--CategoryID:TYPOS, RuleID: POSSESSIVE_APOSTROPHE-->
  ```
  ...a 'multicore-sdr' option is used in the proofs library.  This feature is als...
                                             ^^^^^^
  ```
- The operating system from Apple is written “macOS”.<!--CategoryID:GRAMMAR, RuleID: MAC_OS-->
  ```
  ...efault and not visible in journalctl. # MacOS These instructions are specifi...
                                             ^^^^^
  ```
- Possibly missing comma found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_COMMA-->
  ```
  ...by building from source. # Install with Homebrew You can quickly install Lot...
                                             ^^^^^^^^
  ```
- The verb ‘check out’ is spelled as two words. The noun ‘checkout’ is spelled as one.<!--CategoryID:TYPOS, RuleID: CAN_CHECKOUT-->
  ```
  ...sitory:  Run git checkout <RELEASE TAG> to checkout to the latest Lotus rele...
                                             ^^^^^^^^^^^
  ```
- The verb ‘check out’ is spelled as two words. The noun ‘checkout’ is spelled as one.<!--CategoryID:TYPOS, RuleID: CAN_CHECKOUT-->
  ```
  ...GitHub release page  (opens new window) to checkout to that specific release...
                                             ^^^^^^^^^^^
  ```
- The verb ‘check out’ is spelled as two words. The noun ‘checkout’ is spelled as one.<!--CategoryID:TYPOS, RuleID: CAN_CHECKOUT-->
  ```
  ... that specific release. TIP If you want to checkout to a network other than ...
                                             ^^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... other than mainnet, take a look at the Switching networks guide → Create ne...
                                             ^^^^^^^^^
  ```
- Possibly missing article found.<!--CategoryID:MISC, RuleID: AI_HYDRA_LEO_MISSING_THE-->
  ```
  ...t the Switching networks guide → Create necessary environment variable to al...
                                             ^^^^^^^^^
  ```
- The verb ‘check out’ is spelled as two words. The noun ‘checkout’ is spelled as one.<!--CategoryID:TYPOS, RuleID: CAN_CHECKOUT-->
  ```
  ...sitory:  Run git checkout <RELEASE TAG> to checkout to the latest Lotus rele...
                                             ^^^^^^^^^^^
  ```
- The verb ‘check out’ is spelled as two words. The noun ‘checkout’ is spelled as one.<!--CategoryID:TYPOS, RuleID: CAN_CHECKOUT-->
  ```
  ...GitHub release page  (opens new window) to checkout to that specific release...
                                             ^^^^^^^^^^^
  ```
- The verb ‘check out’ is spelled as two words. The noun ‘checkout’ is spelled as one.<!--CategoryID:TYPOS, RuleID: CAN_CHECKOUT-->
  ```
  ... that specific release. TIP If you want to checkout to a network other than ...
                                             ^^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).<!--CategoryID:CASING, RuleID: EN_UPPER_CASE_NGRAM-->
  ```
  ... other than mainnet, take a look at the Switching networks guide → If you ar...
                                             ^^^^^^^^^
  ```
- Unpaired symbol: ‘"’ seems to be missing<!--CategoryID:PUNCTUATION, RuleID: EN_UNPAIRED_BRACKETS-->
  ```
  ... at some tips for running Lotus in China". Some older Intel and AMD processo...
                                             ^
  ```
- The ph [...]

2021-09-20 14:28 UTC, johnnymatthews approved these changes

2021-09-20 15:40 UTC, merged