Doc for 1.11.2
filecoin-project/filecoin-docs pull request #1058
Opened 2021-09-22 09:40 UTC by dayou5168

Doc for 1.11.2. modify format with VSCode Markdownlint. and update some content

2021-09-22 09:44 UTC, dayou5168 commented
Closes #1033

2021-10-05 15:26 UTC, johnnymatthews requested changes

2021-10-05 15:26 UTC, johnnymatthews commented on docs/mine/lotus/miner-addresses.md
> +5. You can Specify other actor to check control address:
```suggestion
5. You can specify other actor to check control address:
```

2021-10-05 15:26 UTC, johnnymatthews commented on docs/mine/lotus/miner-configuration.md
> +For example if you want to set the sector lifecycle to 180 days, you can multiply 180 days by 24 hours per day to get 4320 hours and set this value to "4320h0m0s".
```suggestion
For example, if you want to set the sector lifecycle to 180 days, you can multiply 180 days by 24 hours per day to get 4320 hours and set this value to `"4320h0m0s"`.
```

2021-10-05 15:26 UTC, johnnymatthews commented on docs/mine/lotus/sector-pledging.md
> +First you can check the sectors that are about to expire. Sectors that will expire within 60 days can be checked by default with the following command:
```suggestion
You can check which sectors are about to expire. Sectors that will expire within 60 days can be checked by default with the following command:
```

2021-10-05 15:26 UTC, johnnymatthews commented on docs/mine/lotus/sector-pledging.md
> +If you want to check for sectors that will expire within 33 days (669600 epoch in devnet) , add the `--cutoff` option, timing in epoch, here is an example in devnet:
```suggestion
If you want to check for sectors that will expire within 33 days (669600 epoch in devnet) , add the `--cutoff` option along with your desired epoch:
```

2021-10-05 15:26 UTC, johnnymatthews commented on docs/mine/lotus/sector-pledging.md
> +```
````suggestion
```shell output
ID  SealProof  InitialPledge  Activation                      Expiration                  MaxExpiration                 MaxExtendNow                  
5   5          59.605 nFIL    1519 (1 day 9 hours ago)        691857 (in 4 weeks 2 days)  5257519 (in 34 weeks 3 days)  1587303 (in 10 weeks 2 days)  
10  5          59.605 nFIL    3588 (1 day 7 hours ago)        697617 (in 4 weeks 2 days)  5259588 (in 34 weeks 4 days)  1587303 (in 10 weeks 2 days)  
11  5          59.605 nFIL    4695 (1 day 6 hours ago)        697617 (in 4 weeks 2 days)  5260695 (in 34 weeks 4 days)  1587303 (in 10 weeks 2 days)  
15  5          59.605 nFIL    6891 (1 day 4 hours ago)        700497 (in 4 weeks 2 days)  5262891 (in 34 weeks 4 days)  1587303 (in 10 weeks 2 days)  
17  5          59.605 nFIL    7004 (1 day 3 hours ago)        700497 (in 4 weeks 2 days)  5263004 (in 34 weeks 4 days)  1587303 (in 10 weeks 2 days)
```
````

2021-10-05 15:26 UTC, johnnymatthews commented on docs/mine/lotus/sector-pledging.md
> +```
````suggestion
```shell
lotus-miner sectors check-expire --cutoff 669600
```
````

2021-10-05 15:26 UTC, johnnymatthews commented on docs/mine/lotus/sector-pledging.md
> +```
````suggestion
```shell
lotus-miner sectors renew [command options] [arguments...]
```
````

2021-10-05 15:26 UTC, johnnymatthews commented on docs/mine/lotus/sector-pledging.md
> +:::
````suggestion
::: warning
You have to select the sectors to renew. That means you have to specify the `--from` and `--to` option, or specify the sector file, if no sector is selected this command will have no effect.

Format of sector file:

```  
1  
2  
...
```  
:::
````

2021-10-05 15:27 UTC, johnnymatthews commented
This is a great PR! Sorry it took a few days to get around to reviewing it. I've submitted a few minor changes.

2021-10-05 15:28 UTC, johnnymatthews approved these changes

2021-10-05 16:04 UTC, johnnymatthews commented on docs/mine/lotus/sector-pledging.md
> +```shell
````suggestion
```shell with-output
````

2021-10-05 16:04 UTC, johnnymatthews commented on docs/mine/lotus/sector-pledging.md
> +```shell
````suggestion
```shell with-output
````

2021-10-05 16:08 UTC, merged