Updated copyright info for README
filecoin-project/filecoin-docs pull request #1255
Opened 2022-05-11 01:05 UTC by dawnkelly09

Per feedback from legal Fixes #1251

2022-05-11 16:26 UTC, dawnkelly09 commented
This is waiting on final clarification from Legal team. Do not merge yet! Thanks!

2022-05-12 16:14 UTC, johnnymatthews commented
Converted this PR to draft, just until it's ready for review.

2022-05-16 15:23 UTC, johnnymatthews commented on readme.md
> +
```suggestion
```

2022-05-16 15:23 UTC, johnnymatthews commented on readme.md
> +- [@cwaring](https://github.com/cwaring): Development support
```suggestion
```

2022-05-16 15:24 UTC, johnnymatthews commented on readme.md
> +
```suggestion
# Filecoin Docs
```

2022-05-16 15:25 UTC, johnnymatthews commented on readme.md
> +# Filecoin Docs
```suggestion
# Filecoin Docs

```

2022-05-16 15:57 UTC, mishmosh commented
I think this PR is now outdated (since it adds the README.md file afresh, which was completed in #1249. Should merge `main` into this branch?

2022-05-16 20:18 UTC, johnnymatthews commented
Just merged `main` into this branch, so everything's all caught up now.

2022-05-16 20:48 UTC, mishmosh commented
@dawnkelly09 It's because you created this branch from `main` before #1249 was merged, so to github it looks like you're effectively PRing the entire new readme.md file twice. 

More info here: https://docs.gpcrdb.org/git_workflow.html

2022-05-16 20:53 UTC, dawnkelly09 commented
Please just confirm if we are all happy with this so it can be merged. Or if it is better to just close it at this point. Thank you!

2022-05-16 21:04 UTC, mishmosh requested changes
Suggestions made for lines 60-63.

2022-05-16 21:04 UTC, mishmosh commented on readme.md
> +Apache License, Version 2.0, (LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0)
This repeats info already contained in line 60. `LICENSE-APACHE` would usually link to a new file containing a copy of the license, but for simplicity's sake let's not create new license files solely for the docs project, we can link to the published versions.

2022-05-16 21:58 UTC, merged