Update/wallaby instances
filecoin-project/filecoin-docs pull request #1584
Opened 2023-01-19 15:21 UTC by johnnymatthews

Closes https://github.com/filecoin-project/filecoin-docs/issues/1571

2023-01-19 15:43 UTC, johnnymatthews commented
This'll get merged, pending no errors from Fleek.

2023-01-19 16:11 UTC, johnnymatthews commented
Had to revert back to `v0` to APIs. This is ready for review.

2023-01-19 17:09 UTC, jennijuju commented on content/en/developers/infrastructure/networks/index.md
> +Mainnet is the primary Filecoin network. Mainnet began on block 148,888. It supports 32 GiB and 64 GiB sectors.
```suggestion
Mainnet is the primary Filecoin network. Mainnet began on block 148,888. It supports 32 GiB and 64 GiB sectors.
```

Is there a reason why we added the liftoff epoch?

2023-01-19 17:22 UTC, jennijuju commented on content/en/developers/smart-contracts/how-tos/add-to-metamask/index.md
> +    | New RPC URL | `https://api.hyperspace.node.glif.io/rpc/v0` |
have talked to glif - confirmed will only serve eth api on v1 after todays patch, so lets update the endpoint

2023-01-19 17:23 UTC, jennijuju requested changes

2023-01-19 17:23 UTC, jennijuju commented on content/en/developers/smart-contracts/how-tos/add-to-metamask/index.md
> +    - Filscan: `https://explorer.glif.io/?network=hyperspace`
this points glif?

2023-01-19 17:25 UTC, jennijuju commented on content/en/developers/reference/json-rpc/eth/index.md
> +curl --location --request POST 'https://api.hyperspace.node.glif.io/rpc/v0' \
I am not a huge fan  that the docs should point in testnet by defualt - do we plan to change this back when fevm launch in mainnet? if so, can we open an issue to make sure we dont forget about it?

2023-01-19 17:28 UTC, jennijuju commented on content/en/developers/smart-contracts/how-tos/add-to-metamask/index.md
>      | Chain ID | `31415` |
```suggestion
    | Chain ID | `3141` |
```

2023-01-19 18:07 UTC, johnnymatthews commented
Commits changes and suggestions from @jennijuju. Can merge, pending a 2nd approval.

2023-01-19 18:17 UTC, jennijuju commented on content/en/networks/overview/available-networks/index.md
> +## Block explorers
```suggestion
### Block explorers
```

2023-01-20 05:59 UTC, jennijuju requested changes

2023-01-20 05:59 UTC, jennijuju commented on content/en/developers/infrastructure/networks/index.md
> +**FVM release**:
These information are wrong- please remove

2023-01-20 05:59 UTC, jennijuju commented on content/en/developers/infrastructure/networks/index.md
> +- [Slack Channel for Updates: #fil-network-announcements](https://filecoinproject.slack.com/archives/C01AC6999KQ)
```suggestion
- [Slack Channel for Updates/questions: #fil-net-hyperspace-discuss](https://filecoinproject.slack.com/archives/C01AC6999KQ)
```

2023-01-20 05:59 UTC, jennijuju commented on content/en/developers/infrastructure/networks/index.md
> +- [Slack Channel for Questions: #fil-help](https://filecoinproject.slack.com/archives/CEGN061C5)
```

2023-01-20 14:44 UTC, merged