Issue 1666 - future proofing smart contracts
filecoin-project/filecoin-docs pull request #1691
Opened 2023-02-24 00:28 UTC by ElPaisano

Addresses issue 1666.

Created a new page under Developers -> Smart Contracts -> How Tos based off of https://github.com/filecoin-project/testnet-hyperspace/issues/9

2023-02-24 00:30 UTC, ElPaisano commented
@johnnymatthews can you give this a review and let me know if I'm on the right track here?

2023-03-01 18:59 UTC, johnnymatthews commented on content/en/developers/smart-contracts/how-tos/future-proof/index.md
> +**Developers should take the time to thoroughly read through the following summary of possible contract future-proofing updates, as failure to properly future proof smart contracts may result in inco
Maybe add this into an alert shortcode? So something like:

```suggestion
{{< alert >}}
Developers should take the time to thoroughly read through the following summary of possible contract future-proofing updates, as failure to properly future proof smart contracts may result in incompatibility with the [v1.20.0-hyperspace-nv20 release](https://github.com/filecoin-project/testnet-hyperspace/issues/9) and future Filecoin releases.
{{< /alert >}}
```

2023-03-01 18:59 UTC, johnnymatthews requested changes
Looks good. Just need to address a couple of comments I left.

2023-03-02 23:31 UTC, ElPaisano commented on content/en/developers/smart-contracts/how-tos/future-proof/index.md
> +lead: "Learn how to future-proof an existing smart contract for compatibility with the `v1.20.0-hyperspace-nv20` release and future network upgrades."
Removed in https://github.com/filecoin-project/filecoin-docs/pull/1691/commits/9d3935f4918953bfa602a8a17345722b17cfdf95

2023-03-02 23:32 UTC, ElPaisano commented
> Looks good. Just need to address a couple of comments I left.

Alright comments addressed, should be good to merge

2023-03-06 17:06 UTC, johnnymatthews approved these changes

2023-03-06 21:48 UTC, ElPaisano commented
@johnnymatthews I don't have merge capabilities even with the approval

![image](https://user-images.githubusercontent.com/113373882/223242286-918b703f-ca9f-4b04-9099-0b70fefc21c1.png)

2023-03-08 16:06 UTC, merged