TODO STEF resolution pass
filecoin-project/filecoin-docs pull request #1883
Opened 2023-04-02 16:19 UTC by smagdali

I've done another pass on TODO STEF comments. I've resolved some, and marked some as NOBLOCK if I don't think they're blockers to going live, and some as BOB where I think we could resolve quickly if @bobdubois and I worked discussed them live together, maybe on Monday morning. 

Some I've asked questions on slack to get answers I can plug in later. 

Also some more linty fixes.

2023-04-02 21:15 UTC, ElPaisano requested changes
Hey Stef, did a first pass through all of this. If it helps, I can do another pass with some linters I use once you and Bob have added in what you'd like to, Vale for spelling / duplicate words and markdown-link-check for external links. 

If you have any questions or comments about any suggestions made (or if you disagree or my suggestion is incorrect), please lmk and I am happy to discuss further. Also, I went through this pretty quick, so some of my own comments may be confusingly worded or formatted 😅 lmk

In this review, instead of directly making changes, I just made suggestions. However, I do think that the majority of these should be implemented before this is published. If it helps the team, I'm happy to implement all of these directly or, if the team would like to decide what they want, just implement the agreed upon changes. Or, the team can make the changes themselves - whatever works for y'all. Main thing is that I don't want to be a blocker to getting this published, so lmk what helps the most

A few general callouts:

1. Capitalization and formatting of terms: there's a general inconsistency throughout the PR in how terms (i.e. Storage Providers) are capitalized (fully, partially, or not at all) and formatted (quotes, italics, not at all, etc.). We should pick one or define a consistent rule.
2. Introduction of terms: in general, introduce the full term first i.e. Committed Capacity, followed by the abbreviation in parens i.e. (CC). I've noticed this also was inconsistent throughout the branch https://docs.ipfs.tech/community/contribute/grammar-formatting-and-style/#grammar-and-spelling
3. Headers. This is based off of the [ipfs-docs style guide](https://docs.ipfs.tech/community/contribute/grammar-formatting-and-style/#titles) (which I believe was the same as what we had in filecoin-docs at one point):

    - header capitalization is inconsistent. Unless it's a term like "Big Data Exchange", only the first word should be capitalized
   - remove special characters like "&"
   - remove punctuation like "?", rewrite

4. Use bold text for buttons, hyperlinks, images with text in them, window names, and icons. https://docs.ipfs.tech/community/contribute/grammar-formatting-and-style/#style

https://docs.ipfs.tech/community/contribute/grammar-formatting-and-style/#grammar-and-spelling

I'm cc'ing @johnnymatthews on these to sanity check me here (johnny please lmk if I'm incorrect here). Wanted to point to the docs grammar / styling guide as the source of truth, but it appears to have been removed? https://docs.filecoin.io/basics/project-and-community/ways-to-contribute/#writing-guide. I generally based my review off of https://docs.ipfs.tech/community/contribute/grammar-formatting-and-style/#grammar-and-spelling, which I seem to recall was basically the same style guide as Fil docs

2023-04-03 12:41 UTC, smagdali commented on content/en/storage-provider/architecture/Lotus-components/index.md
>  The remaining worker tasks are running [Sealing Pipeline]({{<relref "sealing-pipeline">}}) which is discussed in the next section.
also fixed the Sealing Pipeline incorrect captilisation

2023-04-03 14:01 UTC, smagdali commented on content/en/storage-provider/filecoin-deals/verified-deals/index.md
> +If the Storage Provider is then not capable of keeping the data and systems online and fails to submit the daily required proofs (WindowPoSt) for that data, the penalties ('slashing') are also 10x hi
Yup, I'm not a fan of alleged "quotes" either :)

2023-04-03 16:06 UTC, ElPaisano commented
Howdy @smagdali remaining edits made in https://github.com/filecoin-project/filecoin-docs/pull/1883/commits/287c27d1df0907794b4248ebd2701a7774d0c540 🚀 

Note that I found a few more (super nitpicky) things, which I also corrected in here.

Please lmk if there are any concerns here or if you need anything else on this one. Thank you

2023-04-03 16:56 UTC, smagdali reviewed
LGTM

2023-04-03 18:21 UTC, merged