Include Forest 🌲 snapshot links
filecoin-project/filecoin-docs pull request #1991
Opened 2023-05-23 19:48 UTC by lerajk

This PR contains snapshot links to be included from the Forest 🌲 node (maintained by ChainSafe).

2023-05-24 00:15 UTC, smagdali requested changes
Do you want to add some explanation of the difference between the two, and make 'Forest by Chainsafe" a link to the project home page, or more info? 

(but thanks for fixing the 'snapsnot' typo :) )

2023-05-24 17:45 UTC, smagdali approved these changes

2023-05-31 15:03 UTC, johnnymatthews commented on content/en/networks/calibration/details/index.md
> +- [Latest lightweight snapshot](https://forest.chainsafe.io/calibnet/snapshot-latest) generated with [Forest 🌲](http://github.com/ChainSafe/forest) by [ChainSafe](https://chainsafe.io/)
```suggestion
- [Latest lightweight snapshot](https://forest.chainsafe.io/calibnet/snapshot-latest) generated with [Forest](http://github.com/ChainSafe/forest) by [ChainSafe](https://chainsafe.io/)
```

2023-05-31 15:03 UTC, johnnymatthews commented on content/en/networks/mainnet/details/index.md
> +- [Latest lightweight snapshot](https://forest.chainsafe.io/mainnet/snapshot-latest) generated with [Forest 🌲](http://github.com/ChainSafe/forest) by [ChainSafe](https://chainsafe.io/)
```suggestion
- [Latest lightweight snapshot](https://forest.chainsafe.io/mainnet/snapshot-latest) generated with [Forest](http://github.com/ChainSafe/forest) by [ChainSafe](https://chainsafe.io/)
```

2023-05-31 15:04 UTC, johnnymatthews approved these changes
Removed the tree 🌲 emoji. It's cute, but it doesn't work well with translation services/extensions.

The rest of this looks good to me.

2023-05-31 15:04 UTC, merged