Msig
filecoin-project/filecoin-docs pull request #539
Opened 2020-11-03 04:17 UTC by jennijuju

requires format update.

2020-11-03 15:36 UTC, johnnymatthews requested changes

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +Multisig(multi-signature) wallet refers to a wallet that requires multiple keys to authorize a FIL transactions.
```suggestion
A multisig (multi-signature) wallet refers to a wallet that requires multiple keys to authorize a `FIL` transactions.
```

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +To create a multisig, run
```suggestion
Use `lotus msig create` to a multisig wallet:
```

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +```
````suggestion
```bash
lotus msig create signerAddress1 signerAddress2 signerAddress3...

> Created new multisig:  f01002 f24mscgjtgymb3dqtm4ycwydh4nhygktgxm3nbgva
```
````

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +where `f01002` is the id address and `f24mscgjtgymb3dqtm4ycwydh4nhygktgxm3nbgva` is the actor address, both addresses represent the newly created multisig wallet.
```suggestion
In the above example, `f01002` is the id address and `f24mscgjtgymb3dqtm4ycwydh4nhygktgxm3nbgva` is the actor address. Both addresses represent the newly created multisig wallet.
```

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +By default, signatures from all signers are required for approving a transaction, however, the number of required approvals can be customized by passing in the `--required` option upon creation:
```suggestion
By default, signatures from all signers are required for approving a transaction. However, you can change the number of required approvals by using the `--required` option:
```

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +The above command creates a multisig wallet that has 3 signers, and 2 approvals are required for a transaction to be executed.
```suggestion
The above example creates a multisig wallet with three signers, but only requires two approvals for the transaction to be executed.
```

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +Any signer of the multisig wallet can propose a transaction. The proposer approves the transaction upon proposal. The transaction will only be executed when the amount of approvals received equals to
```suggestion
Any signer of the multisig wallet can _propose_ a transaction. The _proposer_ automatically approves the transaction upon proposal. The transaction will only be executed when the amount of approvals received equals to the amount of required approvals. A [multisig wallet can be inspected](#inspect-a-multisig-wallet) to get the number of required approvals. If the multisig wallet only requires one signer, then the transaction will be executed once the transaction is proposed.
```

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +You can propose a transaction to a multisig wallet that you are a signer of by running
```suggestion
Use `lotus msig propose` to propose a transaction:
```

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +```
```suggestion
```bash
lotus msig propose --from=proposerAddress walletAddress destinationAddress value

> send proposal in message:  bafy2bzaceajm2mghc5rludlbcr3bnpqgcz5m6gmldq6ycrc4trkejz36tnrqe
Transaction ID: 0
```

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +where the `bafy2bzaceajm2mghc5rludlbcr3bnpqgcz5m6gmldq6ycrc4trkejz36tnrqe` is the `messageID` and `0` is the transaction id.
```suggestion
In the above example `bafy2bzaceajm2mghc5rludlbcr3bnpqgcz5m6gmldq6ycrc4trkejz36tnrqe` is the `messageID`, and `0` is the `transactionID`.
```

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +Other signers can approved the messages by running:
```suggestion
Other signers can use `lotus msig approve` to approve the messages:
```

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +Note that the value of `transactionID`, `proposerAddress`, `destinationAddress` and `value` must all match the proposal params.
```suggestion
The value of `transactionID`, `proposerAddress`, `destinationAddress` and `value` must match the values used in the proposal.
```

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +To get the information of a multisig wallet, run
```suggestion
Use `lotus msig inspect` to get information about the multisig wallet:
```

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +lotus msign inspect walletaddress
```suggestion
lotus msig inspect walletaddress
```

@jennijuju typo?

2020-11-03 15:36 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +```
```suggestion

> Balance: 0 FIL
> Spendable: 0 FIL
> Threshold: 2 / 3 # amount of signature required / amount of signers the wallet has
> Signers:
> ID      Address
> t01001  t1ai2gcr2xlpyxcbjlegojbpr3ovdyfdyzigjoyza
> t0100   t3r4d3avth4agwxy6ko35reeuydcqaa6cq4mt6owg3zjq23pxqc6xvn7scb43dyhaf2cjnjhtioek6innbpgda
> t01003  t3rpukrggza4jjt6vpihiqoekth6tiopzhvxbp36qhrzfu4xpk6n3mxo5geh6bdavkkkhqk7owt2an2wrundtq
> Transactions:  1
> ID      State    Approvals  To                                         Value   Method   Params
> 0       pending  1          t1fjswymsauvfh5zxw34t2pgz7iev2fn56unyw6ci  20 FIL  Send(0)
```
```

2020-11-06 16:52 UTC, johnnymatthews approved these changes

2020-11-10 22:39 UTC, johnnymatthews commented
Closes #523

2020-11-16 17:22 UTC, arajasek approved these changes
Some nits

2020-11-16 17:22 UTC, arajasek commented on docs/get-started/lotus/multisig.md
> +The above example creates a multisig wallet with three signers, but only requires two approvals for the transaction to be executed.
```suggestion
The above example creates a multisig wallet with three signers, but only requires two approvals for a transaction to be executed.
```

2020-11-16 17:22 UTC, arajasek commented on docs/get-started/lotus/multisig.md
> +Any signer of the multisig wallet can _propose_ a transaction. The _proposer_ automatically approves the transaction upon proposal. The transaction will only be executed when the amount of approvals
```suggestion
Any signer of a multisig wallet can _propose_ a transaction. The _proposer_ automatically approves a transaction upon proposal. A transaction will only be executed when the number of approvals received equals the number of required approvals. A [multisig wallet can be inspected](#inspect-a-multisig-wallet) to get the number of required approvals. If a multisig wallet only requires one signer, then a transaction will be executed immediately upon its proposal.
```

2020-11-16 17:22 UTC, arajasek commented on docs/get-started/lotus/multisig.md
> +> Threshold: 2 / 3 # amount of signature required / amount of signers the wallet has
```suggestion
> Threshold: 2 / 3 # number of signature required / number of signers the wallet has
```

2020-11-17 18:39 UTC, johnnymatthews approved these changes

2020-11-17 18:39 UTC, johnnymatthews commented on docs/get-started/lotus/multisig.md
> +A multisig (multi-signature) wallet refers to a wallet that requires multiple keys to authorize a `FIL` transactions.
```suggestion
A multi-signature (multisig) wallet refers to a wallet that requires multiple keys to authorize a `FIL` transactions.
```

2020-11-17 18:42 UTC, johnnymatthews commented
Commited @arajasek's suggestions. Looks good from my end. Merge when ready.

2020-11-18 19:55 UTC, merged