Update sector-pledging.md
filecoin-project/filecoin-docs pull request #564
Opened 2020-11-06 06:39 UTC by jennijuju

2020-11-06 08:10 UTC, arajasek approved these changes
Let's add that the default is 18 months?

2020-11-09 23:25 UTC, johnnymatthews requested changes

2020-11-09 23:25 UTC, johnnymatthews commented on docs/mine/lotus/sector-pledging.md
> +The pledge period for the sector can be around 6-18 months(18 months by default). The _upgrading_ process allows however to recover pledged sectors for re-use much more quickly. The following command
```suggestion
The pledge period for the sector can be between 6 to 18 months. 18 months is the default. The _upgrading_ process allows however to recover pledged sectors for re-use much more quickly. The following command marks a sector for _upgrade_:
```

2020-12-11 04:09 UTC, johnnymatthews commented
Fixed the merge conflict. This good to merge @jennijuju?

2020-12-18 18:37 UTC, merged